// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr1m4GZ9pY9oAF-FDEOkKEfJjc2ONydOM',
    appId: '1:761421169323:web:d6ccf9feb071943a442dee',
    messagingSenderId: '761421169323',
    projectId: 'dgr-alarmes',
    authDomain: 'dgr-alarmes.firebaseapp.com',
    storageBucket: 'dgr-alarmes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvrQ3NbIFWKgzSI0WHXLRXaTtIGz1y3Y',
    appId: '1:761421169323:android:3349b9bd024f79b6442dee',
    messagingSenderId: '761421169323',
    projectId: 'dgr-alarmes',
    storageBucket: 'dgr-alarmes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykTTbIV-uSAkSk2p9Mq3ktv3y7NVJ3tc',
    appId: '1:761421169323:ios:31dc8ff31ed099e8442dee',
    messagingSenderId: '761421169323',
    projectId: 'dgr-alarmes',
    storageBucket: 'dgr-alarmes.appspot.com',
    iosClientId:
        '761421169323-fj6gq5sl3pnbou78ovui3p08bt1gqq0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.DGR_alarmes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBykTTbIV-uSAkSk2p9Mq3ktv3y7NVJ3tc',
    appId: '1:761421169323:ios:31dc8ff31ed099e8442dee',
    messagingSenderId: '761421169323',
    projectId: 'dgr-alarmes',
    storageBucket: 'dgr-alarmes.appspot.com',
    iosClientId:
        '761421169323-fj6gq5sl3pnbou78ovui3p08bt1gqq0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.DGR_alarmes',
  );
}
